format:
  pdf:
    include-in-header:
      - text: |
          # \usepackage{fancyhdr}
          # \usepackage{anyfontsize}
          # \pagestyle{fancy}
          \fancyhf{}
          \renewcommand{\headrulewidth}{0pt} 
          \fancyfoot[R]{\thepage} 
    latex_engine: xelatex
    sansfont: Times New Roman
    fontsize: 12pt
    lineheight: 1.5
    linestretch: 1.5
    geometry: "left=3cm, top=3cm, right=2cm, bottom=2cm"
    number-sections: false
    keep-tex: false

execute:
  freeze: auto

crossref:
  fig-title: Figura   
  fig-prefix: figura
  tbl-title: Tabela     
  tbl-prefix: tabela



