---
title: |
    \fontsize{12pt}{14pt}\selectfont Investigando Fatores Críticos no Desempenho de Fundos de Investimento Imobiliário
authors:
  - name: \fontsize{12pt}{14pt}\selectfont Marcus Antonio Cardoso Ramalho
  - name: \fontsize{12pt}{14pt}\selectfont Ariel Levy
    affiliation: Universidade Federal Fluminense


abstract: lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

bibliography: references.bib
csl: apa.csl
linestretch: 1.5
linkcolor: black
urlcolor: black
toc: true
number-sections: true
---

\thispagestyle{fancy}


## Introdução

O mercado de fundos de investimento imobiliário no Brasil nos últimos anos tem apresentado um crescimento notável, tanto em relação ao número de novos fundos listados quanto em relação ao número de investidores. Isso fica evidente ao se analisar os números presentes nos relatórios mensais da B3, que denotam uma tendência positiva principalmente a partir de 2016 [@b32023]. Apesar de ter um nome diferente no Brasil os FIIs possuem características similares aos REITs (Real Estate Investment Trusts) norte-americanos, que são fundos de investimento imobiliário negociados em bolsa de valores, além disso, este tipo de instrumento financeiro é bastante popular em diversos países ao redor do mundo desde de sua criação em 1960 nos Estados Unidos através do REIT Act, assinado pelo presidente Dwight D. Eisenhower [@ahistor2012]. 

Os FIIs foram criados em 1993 no Brasil e são regulamentados pela Comissão de Valores Mobiliários (CVM) que é o órgão responsável por regular e fiscalizar o mercado de capitais brasileiro. Assim como os REITs, os FIIs são fundos que em ativos imobiliários e que tem por característica principal a distribuição da maior parte de seus lucros aos cotistas e a isenção de imposto de renda sobre os rendimentos distribuídos. 

Acompanhando o crescimento do mercado de fundos imobiliários, pesquisadores tem se interessado cada vez mais em investigar este tipo de ativo. Conforme apontado por @weise2017, o número de publicações sobre o tema apresentou um crescimento constante a partir do início dos anos 2000 o que vai de encontro aos apontamentos de @ahistor2012 que comenta sobre como os REITs se consolidaram como um instrumento financeiro popular e de grande interesse no mesmo período.

Assim como qualquer tipo de ativo financeiro, os fundos imobiliários estão sujeitos a riscos inerentes tanto ao próprio mercado quanto a fatores macroeconômicos que variam de acordo com o país. Em uma análise bibliométrica sobre o tema, @teófilo2022 identificou indícios de de uma certa concentração sobre temas de artigos relacionados ao sentimento dos investidores e a análise de desempenho dos fundos quanto ao risco e retorno. Visto que esse tipo de análise já tem sido explorada amplamente na literatura, abre-se a oportunidade para investigar outros fatores que possam influenciar o desempenho dos fundos imobiliários, como por exemplo a influência de fatores macroeconômicos e influência de outras variáveis que geralmente não são consideradas em estudos sobre o tema como a popularidade dos fundos entre os investidores. 

Considerando a importância do tema e a popularidade dos fundos imobiliários no Brasil e no mundo este trabalho tem como objetivo explorar as variáveis que influenciam os fundos de investimento imobiliário quanto ao seu desempenho e a sua relação com o crescimento do mercado ao longo do tempo com foco no efeito das variáveis macroeconômicas, popularidade e pagamento de dividendos como fatores críticos no desempenho ou retorno dos fundos.

Para isso, este trabalho se propõe a desenvolver uma revisão sitemática da literatura usando o método PRISMA [@page2021] nas bases indexadas Web of Science, Scopus e Periódicos Capes. 

Para alcançar os objetivos propostos, foram consideradas as seguintes perguntas de pesquisa: Como a distribuição de dividendos afeta os retornos? Como os fundos reagem a períodos de crise econômica? Como mudanças na economia afetam o desempenho? Como a popularidade é afetada pelo Youtube? Quais são as variáveis mais estudadas na literatura?

<!-- adicionar aqui as conclusões -->

## Metodologia 

A pesquisa foi realizada com o auxílio de algumas ferramentas, como o Parsifal [@misc], que é um sistema online de apoio à revisão sistemática da literatura utilizando o método PRISMA (Preferred Reporting Items for Systematic reviews and Meta-Analyses) que é uma metodologia criada para direcionar o desenvolvimento de revisões sistemáticas da literatura [@page2021]. A @fig-processo-metodologico apresenta o fluxograma do processo que foi seguido para a realização do trabalho.

::: {#fig-processo-metodologico fig-cap="Fluxograma do processo metodológico - Elaboração própria"}

```{mermaid}
%%| fig-width: 6.5
graph LR;
    A{Definição <br> objetivos} --> B{Definição <br> PICOC};
    B --> C{Definição das Perguntas};
    C --> D{Definição de <br> palavras-chave e <br> sinônimos};
    D --> E{Definição de String e <br> busca nas bases};
    E --> F[Análise a partir dos <br> critérios de <br> inclusão];
    F --> G[Leitura e <br> Análise de <br> Qualidade dos <br> artigos];
    G --> H[(Extração de <br> dados)];

```
<!-- aqui elaborar mais a metodologia prisma considerando os passos do método para a esta pesquisa -->

:::


<!-- revisar -->

A primeira etapa do processo foi a definição dos objetivos da pesquisa. Em seguida, foi definido o PICOC (Population, Intervention, Comparison, Outcome e Context) que são os elementos que compõem a pergunta de pesquisa. A partir do PICOC, foram definidas as perguntas de pesquisa que nortearam a revisão sistemática.

As palavras-chave e sinônimos foram definidos para identificar os termos usados na pesquisa nas bases de dados. A partir destes, a string de busca foi construída. Com ela, realizamos a pesquisa nas bases de dados.

### PICOC e perguntas de pesquisa

Nesta etapa cada um dos elementos do PICOC foi definido conforme a seguir: 

- **Population**: Fundos de investimento imobiliário
- **Intervention**: Análise dos indicadores de desempenho
- **Comparison**: Comparação entre as variáveis que podem influenciar o desempenho dos fundos
- **Outcome**: Entender quais são as variáveis que influenciam o desempenho dos fundos
- **Context**: Mercado de fundos de investimento imobiliário

A partir destes elementos, foram definidas as perguntas de pesquisa que nortearam a revisão sistemática e que foram utilizadas para a construção da string de busca.

1. Como a distribuição de dividendos afeta os retornos?
2. Como os fundos reagem a períodos de crise econômica?
3. Como mudanças na economia afetam o desempenho?
4. Como os influencidadores do Youtube afetam a popularidade dos fundos?
5. Quais são as variáveis mais estudadas na literatura?

### Definição de palavras-chave e sinônimos

| Keyword                      | Synonyms                                                                 |
|------------------------------|--------------------------------------------------------------------------|
| Comparison between variables | Correlation, Endogenous factors, Exogenous factors, Inference, Relationship |
| Growth                       | Changes, Crescimento, Decline, Fall, Rise                               |
| Performance                  | Yield, returns                                                           |
| Real state investiment funds | FII, Fundos de investimento imobiliário, REITS, Real estate funds, Real estate investment trusts, Real state investment funds |
| Social media                 | Instagram, Twitter, Youtube, facebook                                   |

Foram criadas as seguintes strings de busca para cada base de dados:

Scopus e WOS

("Real state investiment funds" OR "FII" OR "Fundos de investimento imobiliário" OR "REITS" OR "Real estate funds" OR "Real estate investment trusts" OR "Real state investment funds") AND ("Performance" OR "Yield" OR "returns" OR "Social media" OR "Instagram" OR "Twitter" OR "Youtube" OR "facebook") AND ("Comparison between variables" OR "Correlation" OR "Endogenous factors" OR "Exogenous factors" OR "Inference" OR "Relationship") AND ("Growth" OR "Changes" OR "Crescimento" OR "Decline" OR "Fall" OR "Rise")



CAPES:

("Fundos de investimento imobiliário" OU "FII" OU "Fundos de investimento imobiliário" OU "REITS" OU "Fundos imobiliários" OU "Trustes de investimento imobiliário" OU "Fundos de investimento imobiliário") E ("Desempenho" OU "Rendimento" OU "retornos" OU "Mídias sociais" OU "Instagram" OU "Twitter" OU "Youtube" OU "facebook") 

### Critérios de inclusão



### Critérios de exclusão

### Análise de qualidade dos artigos

### Extração de dados

## Resultados

## Discussão

## Conclusão


## Referências